---
title: "Cortina-Camila-ADA-homework-1"
author: "Camila Cortina"
date: "2/4/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
##Challenge 1
```{r}
library(stringr)
quote<- as.vector("There grandeur in this view of life, with its several powers, having been originally breathed by the Creator into a few forms or into one; and that, whilst this planet has gone circling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being evolved")
quote<- gsub("[[:punct:]]","", quote)

split_quote<- str_split(quote, " ")
split_quote<- split_quote[[1]]
split_quote

every_fourth<- split_quote[seq(from = 1, to = length(split_quote), by = 4)]
every_fourth

every_fourth<- sort(every_fourth, decreasing = TRUE)
every_fourth
```

##Challenge 2
```{r}
m1<- matrix(data = seq(from = 1, to = 159, by = 2), nrow = 8, ncol = 10, byrow = FALSE)
m1

m1[5,2]

m1[5:7,]

m2<- m1[3:6, 4:9]
m2

class(m2) #The class of m2 is a matrix
mode(m2) #The mode of m2 is numeric 
```

##Challenge 3
```{r}
a<- array(data = 400:1, dim = c(5, 5, 4, 4))
a

a[1,1,1,2] #Returns a single number within the array
a[2,3,2,] #Returns all of the numbers found at the second row third column of the second matrix within each array
a[1:5, 1:5, 3, 3] #Returns the third matrix in the third array
```

##Challenge 4
```{r}
#Superfamilies
Superfamily_Lorisodae<- c("Lorisidae", "Galagidae")
Superfamily_Lemuroidea<- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")
Superfamily_Tarsioidea<- c("Tarsiidae")
Superfamily_Ceboidea<- c("Cebidae", "Atelidae", "Pitheciidae")
Superfamily_Hominoidea<- c("Hylobatidae", "Hominidae")
Superfamily_Cercopithecoidea<- c("Cercopithecidae")
#Pavorders
Pavorder_Platyrrhini<- list(Superfamily_Ceboidea)
names(Pavorder_Platyrrhini)<- c("Superfamily_Ceboidea")
Pavorder_Catarrhini<- list(Superfamily_Hominoidea, Superfamily_Cercopithecoidea)
names(Pavorder_Catarrhini)<- c("Superfamily_Hominoidea", "Superfamily_Cercopithecoidea")
#Infraorders
Infraorder_Lemuriformes<- list(Superfamily_Lemuroidea)
names(Infraorder_Lemuriformes)<- c("Superfamily_Lemuroidea")
Infraorder_Lorisiformes<- list(Superfamily_Lorisodae)
names(Infraorder_Lorisiformes)<- c("Superfamily_Lorisodae")
Infraorder_Tarsiiformes<- list(Superfamily_Tarsioidea)
names(Infraorder_Tarsiiformes)<- c("Superfamily_Tarsioidea")
Infraorder_Simiiformes<- list(Pavorder_Platyrrhini, Pavorder_Catarrhini)
names(Infraorder_Simiiformes)<- c("Pavorder_Platyrrhini", "Pavorder_Catarrhini")
#Suborders
Suborder_Strepsirhini<- list(Infraorder_Lorisiformes, Infraorder_Lemuriformes)
names(Suborder_Strepsirhini)<- c("Infraorder_Lorisiformes", "Infraorder_Lemuriformes")
Suborder_Haplorhini<- list(Infraorder_Tarsiiformes, Infraorder_Simiiformes)
names(Suborder_Haplorhini)<- c("Infraorder_Tarsiiformes", "Infraorder_Simiiformes")
#Order
Order_Primates<- list(Suborder_Strepsirhini, Suborder_Haplorhini)
names(Order_Primates)<- c("Suborder_Strepsirhini", "Suborder_Haplorhini")

nwm<- Order_Primates[["Suborder_Haplorhini"]][["Infraorder_Simiiformes"]][["Pavorder_Platyrrhini"]]
nwm
class(nwm) #It is a list
mode(nwm) #The mode is also a list

Order_Primates$Suborder_Haplorhini$Infraorder_Tarsiiformes$Superfamily_Tarsioidea
```